name: Deploy Food Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # This pulls your code from GitHub to the server

      - name: Trigger Deployment Script
        run: |
          cd /home/ubuntu/deploy
          ./deploy.sh